name: trust_wallet_desktop
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # AppData packages
  flutter_svg: ^2.0.7
  logger: ^2.0.2+1
  url_launcher: ^6.1.14
  go_router: ^7.1.1
  easy_localization: ^3.0.3
  simple_progress_indicators: ^0.2.0 #Indicator package

  # Core packages
  dio: ^5.3.3
  path_provider: ^2.1.1
  get_it: ^7.6.4
  data_source:
    version: ^0.1.1
    git: https://github.com/dronn1k-org/data_source.git
  reactive_variables: ^0.1.0

  # Domain packages
  json_annotation: ^4.8.1

  # App packages
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  bip39_mnemonic: ^3.0.6
  convert: ^3.1.1
  simple_rc4: ^0.3.0
  fl_chart: ^0.63.0
  hdkey: ^0.0.1
  hex: ^0.2.0
  bip39: ^1.0.6
  web3dart: ^2.7.1
  http: ^1.1.0
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  msix: ^3.16.6
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size

  firebase_core: ^2.24.2 
  cloud_firestore: ^4.14.0
  firebase_database: ^10.4.0
  firedart: ^0.9.7
  connectivity_plus: ^5.0.2

  #Trust packages
  pin_code_fields: ^8.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  retrofit_generator: ^7.0.0
  build_runner: ^2.3.3
  isar_generator: ^3.1.0+1
  hive_generator: ^2.0.1
  flutter_launcher_icons: "^0.13.1"


msix_config:
  display_name: "Trust Wallet : Manager Product"  
  msix_version: 1.0.0.0
  logo_path: snap/gui//trust.png
  publisher_display_name: Coin App Developer
  identity_name: CoinAppDeveloper.ExodusWalletManagerProduct
  publisher: CN=D9B2972A-0816-4529-B776-B3DE1055D45A
  # store: true


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/crypto/
    - snap/gui/
